---
- name:  0 debug host_vars
  debug:
    msg: 'vm_url: {{ vm_url }}; ansible_python_interpreter {{ ansible_python_interpreter }} {{ mw.fullpath }}/maintenance {{mw.script_path}}'


- name: 1 Install aptitude
  package:
    name: aptitude
    state: present

- name: 2 Update and upgrade apt packages
  apt:
    upgrade: 'True'
    update_cache: 'True'
    cache_valid_time: 86400 #One day

- name: 3 Install apt packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-setuptools
    - zip
    - wget
    - git
    - vim
    - nginx
    - apt-transport-https
    - curl
    - tmux
    - lynx
    - mariadb-server
    - python3-mysqldb
    - python3-pymysql
    - python-pymysql
    - php
    - imagemagick

- name: 4 register pip3 executable
  command: which pip3
  register: pip3_path

- name: 5 Configure MariaDB@vm.local
  template:
    src:  mysql.cnf
    dest: /etc/mysql/my.cnf
    mode: o-rw

- name: 6 Start Mysql Service
  service:
    name: mysql
    state: started
    enabled: true

- name: 7 install php extensions
  package:
    pkg: "{{ item }}"
    state: "present"
  loop: "{{ php_extensions }}"
  notify: restart_webserver

- name: 8 download composer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '{{ src_dir }}/composer-setup.php'

- name: 9 setup composer 
  command:
    chdir: '{{ src_dir }}'
    cmd: 'php composer-setup.php --install-dir={{ bin_dir }} --filename=composer'